export enum Action {
  ADD_USER = "ADD_USER",
  REMOVE_USER = "REMOVE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  FETCH_USER = "FETCH_USER",
  FETCH_USERS = "FETCH_USERS",
}
